-- SW:ToR Combat Explorer database schema
--
-- This targets PostgreSQL, currently at v16.9.
--
-- To create a new version:
--
-- 1. Make changes to the schema
-- 2. Change the row in the 'INSERT INTO Version' with the integer
--    to represent the version and the current date/time.
-- 3. Create a git commit for the new version. Do this soon after
--    #2 so the commit timestamp is close to the new Version row.
-- 4. Add a tag to the commit node that indicates the new version of
--    the database: "db vN" where N is the 'id' in the row associated
--    with the new version.

CREATE TABLE Version (
  id INT, -- No semantic version, each row represents the version
  creation TIMESTAMP,
  PRIMARY KEY (id)
);

-- Inserting a row here indicates the version of the database. When you
-- change this row, you should also create a git tag. See the file
-- comments for the procedure.
INSERT INTO Version (id, creation) VALUES
  (1, '2025-08-15 15:51:00');

CREATE TABLE Log_File (
  id SERIAL,
  filename VARCHAR(512),
  creation_ts BIGINT NOT NULL, -- timestamp, ms past the epoch
  fully_parsed BOOL NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
);

-- All of the names we've seen so far
--
-- This is an optimization to avoid storing strings in multiple tables.
-- The 'id' field is directly from the input log entry and is guaranteed
-- unique but is essentially a GUID.
--
-- The first 10 rows in Name are reserved for special system names
--
-- TODO - prepopulate the ability names that are unique to each class.
-- TODO - Add a boolean column indicating the Name is a unique class ability.
CREATE TABLE Name (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 11) PRIMARY KEY,
  name_id DECIMAL(20,0) UNIQUE NOT NULL,
  name VARCHAR (128)
);
CREATE INDEX idx_name_id ON Name(name_id);

-- Special name that represents a value that's not present
--
-- I'd rather not use NULLs. Use id=1 for a "no name provided" value.
INSERT INTO Name (id, name_id, name) VALUES
  (1, 0, 'n/a'),
  (2, 1, 'unknown combat style'),
  (3, 2, 'unknown advanced class'),
  (4, 3, 'no difficulty'),
  (5, 4, 'no area');

-- First 10 rows are reserved for special, system-generated classes

-- TODO: Rename this to the current nomenclature. Except there are two nomenclatures. :/
CREATE TABLE Advanced_Class (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 11) PRIMARY KEY,
  style INT NOT NULL,
  class INT NOT NULL,
  FOREIGN KEY (style) REFERENCES Name(id),
  FOREIGN KEY (class) REFERENCES Name(id),
  UNIQUE (style, class)
);

-- TODO: I should prepopulate this entire table. I know every possible combination already, and the
-- game will never add another class.

-- 2: unknown combat style
-- 3: unknown advanced class
-- id=1: unknown style/class
INSERT INTO Advanced_Class (id, style, class) VALUES
  (1, 2, 3);

CREATE TYPE Actor_Type AS ENUM ('pc', 'npc', 'companion');

-- This table is not normalized as the nullable columns show. This represents every type of Actor, including
-- a PC, an NPC, and a companion. The following fields are valid based on the Actor_Type:
--
-- type = 'pc':
--   name, class
-- type = 'npc':
--   name, instance
-- type = 'companion':
--   name, pc
CREATE TABLE Actor (
  id SERIAL,
  type Actor_Type NOT NULL,
  name INT NOT NULL,
  class INT,
  pc INT,
  instance DECIMAL(20, 0),
  PRIMARY KEY (id),
  FOREIGN KEY (name) REFERENCES Name(id),
  FOREIGN KEY (pc) REFERENCES Actor(id)
);

CREATE TABLE Area (
  id SERIAL,
  area INT NOT NULL,
  difficulty INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (area, difficulty),
  FOREIGN KEY (area) REFERENCES Name(id),
  FOREIGN KEY (difficulty) REFERENCES Name(id)
);

-- id=1: unknown area, no difficulty
INSERT INTO Area (area, difficulty) VALUES
  (5, 4);

CREATE TABLE Combat (
  id SERIAL,
  -- timestamps (ts_*) are stored as ms past the epoch
  ts_begin BIGINT NOT NULL,
  ts_end BIGINT,
  area INT NOT NULL,
  logfile INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (area) REFERENCES Area(id),
  FOREIGN KEY (logfile) REFERENCES Log_File(id)
);

CREATE TYPE Location AS (
  x FLOAT,
  y FLOAT,
  z FLOAT,
  rot FLOAT
);

CREATE TYPE Health AS (
  current INT,
  maximum INT
);

CREATE TABLE Action (
  id SERIAL,
  verb INT NOT NULL,
  noun INT NOT NULL,
  detail INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (verb) REFERENCES Name(id),
  FOREIGN KEY (noun) REFERENCES Name(id),
  FOREIGN KEY (detail) REFERENCES Name(id)
);

CREATE TABLE Event (
  id SERIAL,
  ts BIGINT NOT NULL, -- ms since epoch
  combat INT,
  source INT, 
  source_location Location,
  source_health Health,
  target INT,
  target_location Location,
  target_health Health,
  ability INT,
  action INT NOT NULL,
  value_version VARCHAR(16),
  value_base BIGINT,
  value_crit BOOL,
  value_effective INT,
  value_type INT,
  value_mitigation_reason INT,
  value_mitigation_effect_value INT,
  value_mitigation_effect_value_name INT,
  threat_val INT,
  threat_str VARCHAR(16),
  logfile INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (combat) REFERENCES Combat(id),
  FOREIGN KEY (source) REFERENCES Actor(id),
  FOREIGN KEY (target) REFERENCES Actor(id),
  FOREIGN KEY (ability) REFERENCES Name(id),
  FOREIGN KEY (action) REFERENCES Action(id),
  FOREIGN KEY (value_type) REFERENCES Name(id),
  FOREIGN KEY (value_mitigation_reason) REFERENCES Name(id),
  FOREIGN KEY (value_mitigation_effect_value_name) REFERENCES Name(id)
);
